using UdonSharp;
using UnityEngine;
using Rasta.Tablet;

namespace aki_lua87.AssetsListGenerator
{
    [UdonBehaviourSyncMode(BehaviourSyncMode.NoVariableSync)]
    public class AssetsListRtabApp : TabletAppBehaviour
    {
        [Header("Title Marquee")]
        public bool enableTitleMarquee = true;
        [Min(1f)] public float titleMarqueeSpeed = 300f;
        [Min(0f)] public float titleMarqueeStartDelay = 1.5f;
        [Min(0f)] public float titleMarqueeEndDelay = 0.8f;

        // Generated by AssetsManagerInspector and serialized in the prefab.
        [HideInInspector] public RectTransform[] titleMarqueeTracks;
        [HideInInspector] public float[] titleMarqueeDistances;

        private Vector2[] startPositions;
        private float elapsed;
        private bool isOpen;

        private void Start()
        {
            InitializeMarquee();
        }

        public override void OnAppOpen()
        {
            ResetMarquee();
            isOpen = true;
        }

        public override void OnAppClose()
        {
            isOpen = false;
            ResetMarquee();
        }

        private void Update()
        {
            if (!isOpen || !enableTitleMarquee || titleMarqueeTracks == null || titleMarqueeDistances == null)
                return;

            int count = Mathf.Min(titleMarqueeTracks.Length, titleMarqueeDistances.Length);
            if (startPositions == null || startPositions.Length != count) InitializeMarquee();

            float speed = Mathf.Max(1f, titleMarqueeSpeed);
            float startDelay = Mathf.Max(0f, titleMarqueeStartDelay);
            float endDelay = Mathf.Max(0f, titleMarqueeEndDelay);
            elapsed += Time.deltaTime;

            for (int i = 0; i < count; i++)
            {
                RectTransform track = titleMarqueeTracks[i];
                float distance = titleMarqueeDistances[i];
                if (track == null || distance <= 0f) continue;

                float travelDuration = distance / speed;
                float cycleTime = Mathf.Repeat(elapsed, startDelay + travelDuration + endDelay);
                float offset = 0f;
                if (cycleTime >= startDelay + travelDuration) offset = distance;
                else if (cycleTime > startDelay) offset = (cycleTime - startDelay) * speed;

                Vector2 position = startPositions[i];
                position.x -= offset;
                track.anchoredPosition = position;
            }
        }

        private void InitializeMarquee()
        {
            int count = titleMarqueeTracks == null ? 0 : titleMarqueeTracks.Length;
            startPositions = new Vector2[count];
            for (int i = 0; i < count; i++)
            {
                if (titleMarqueeTracks[i] != null)
                    startPositions[i] = titleMarqueeTracks[i].anchoredPosition;
            }
            elapsed = 0f;
        }

        private void ResetMarquee()
        {
            int count = titleMarqueeTracks == null ? 0 : titleMarqueeTracks.Length;
            if (startPositions == null || startPositions.Length != count) InitializeMarquee();
            elapsed = 0f;
            for (int i = 0; i < count; i++)
            {
                if (titleMarqueeTracks[i] != null)
                    titleMarqueeTracks[i].anchoredPosition = startPositions[i];
            }
        }
    }
}
