
using UdonSharp;
using UnityEngine;

namespace aki_lua87.AssetsListGenerator
{
    [UdonBehaviourSyncMode(BehaviourSyncMode.NoVariableSync)]
    public class TitleMarquee : UdonSharpBehaviour
    {
        [Header("Title Marquee")]
        public bool enableTitleMarquee = true;
        [Min(1f)] public float titleMarqueeSpeed = 300f;
        [Min(0f)] public float titleMarqueeStartDelay = 1.5f;
        [Min(0f)] public float titleMarqueeEndDelay = 0.8f;

        // These references are generated by AssetsManagerInspector and must persist in the prefab.
        [HideInInspector] public RectTransform[] titleMarqueeTracks;
        [HideInInspector] public float[] titleMarqueeDistances;

        private Vector2[] _titleMarqueeStartPositions;
        private float _titleMarqueeElapsed;

        private void Start()
        {
            InitializeTitleMarquee();
        }

        private void OnEnable()
        {
            ResetTitleMarquee();
        }

        private void OnDisable()
        {
            ResetTitleMarquee();
        }

        private void Update()
        {
            if (!enableTitleMarquee) return;
            if (titleMarqueeTracks == null || titleMarqueeDistances == null) return;

            int count = Mathf.Min(titleMarqueeTracks.Length, titleMarqueeDistances.Length);
            if (_titleMarqueeStartPositions == null || _titleMarqueeStartPositions.Length != count)
            {
                InitializeTitleMarquee();
            }

            float speed = Mathf.Max(1f, titleMarqueeSpeed);
            float startDelay = Mathf.Max(0f, titleMarqueeStartDelay);
            float endDelay = Mathf.Max(0f, titleMarqueeEndDelay);
            _titleMarqueeElapsed += Time.deltaTime;

            for (int i = 0; i < count; i++)
            {
                RectTransform track = titleMarqueeTracks[i];
                float distance = titleMarqueeDistances[i];
                if (track == null || distance <= 0f) continue;

                float travelDuration = distance / speed;
                float cycleDuration = startDelay + travelDuration + endDelay;
                float cycleTime = Mathf.Repeat(_titleMarqueeElapsed, cycleDuration);
                float offset = 0f;

                if (cycleTime >= startDelay + travelDuration)
                {
                    offset = distance;
                }
                else if (cycleTime > startDelay)
                {
                    offset = (cycleTime - startDelay) * speed;
                }

                Vector2 position = _titleMarqueeStartPositions[i];
                position.x -= offset;
                track.anchoredPosition = position;
            }
        }

        private void InitializeTitleMarquee()
        {
            int count = titleMarqueeTracks == null ? 0 : titleMarqueeTracks.Length;
            _titleMarqueeStartPositions = new Vector2[count];

            for (int i = 0; i < count; i++)
            {
                RectTransform track = titleMarqueeTracks[i];
                if (track != null)
                {
                    _titleMarqueeStartPositions[i] = track.anchoredPosition;
                }
            }

            _titleMarqueeElapsed = 0f;
        }

        private void ResetTitleMarquee()
        {
            int count = titleMarqueeTracks == null ? 0 : titleMarqueeTracks.Length;
            if (_titleMarqueeStartPositions == null || _titleMarqueeStartPositions.Length != count)
            {
                InitializeTitleMarquee();
            }

            _titleMarqueeElapsed = 0f;
            for (int i = 0; i < count; i++)
            {
                RectTransform track = titleMarqueeTracks[i];
                if (track != null)
                {
                    track.anchoredPosition = _titleMarqueeStartPositions[i];
                }
            }
        }
    }
}

